DROP TABLE ALUNO_OFERTAS;
DROP TABLE TELEFONES;
DROP TABLE OFERTAS;
DROP TABLE DISCIPLINAS;
DROP TABLE PROFESSORES;
DROP TABLE ALUNOS;
CREATE TABLE ALUNOS(
	MATRICULA_ALUNO NUMBER NOT NULL,
	NOME_ALUNO VARCHAR2(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
);
CREATE TABLE TELEFONES(
	TELEFONE VARCHAR2(11) NOT NULL,
	MATRICULA_ALUNO NUMERIC NOT NULL
);
CREATE TABLE PROFESSORES(
	MATRICULA_PROF NUMERIC(5) NOT NULL,
	NOME_PROF VARCHAR2(100) NOT NULL,
	FORMACAO VARCHAR2(100) NOT NULL
);
CREATE TABLE DISCIPLINAS(
	CODIGO_DISCIPLINA NUMERIC NOT NULL,
	NOME_DISCIPLINA VARCHAR2(100) NOT NULL,
	CARGA_HORARIA NUMERIC(3) NOT NULL,
	EMENTA VARCHAR2(4000) NOT NULL,
	CODIGO_DISCIPLINA_DEPENDENCIA NUMERIC NULL
);
CREATE TABLE OFERTAS(
	CODIGO_OFERTA NUMERIC NOT NULL,
	HORARIO_INICIAL TIMESTAMP NOT NULL,
	HORARIO_FINAL TIMESTAMP NOT NULL,
	DIA_SEMANA VARCHAR2(20) NOT NULL,
	MATRICULA_PROF NUMERIC(5) NOT NULL,
	CODIGO_DISCIPLINA NUMERIC NOT NULL
);
CREATE TABLE ALUNO_OFERTAS(
	MATRICULA_ALUNO NUMERIC NOT NULL,
	CODIGO_OFERTA NUMERIC NOT NULL,
	LIMITE_ALUNOS NUMERIC NOT NULL,
	SEMESTRE VARCHAR2(6) NOT NULL,
	DATA_INICIAL DATE NOT NULL,
	DATA_FINAL DATE NOT NULL
);

CREATE VIEW DISCIPLINAS_PROFESSOR AS
SELECT P.NOME_PROF AS PROFESSOR
	, P.FORMACAO
	, D.CODIGO_DISCIPLINA
	, D.NOME_DISCIPLINA
	, D.CARGA_HORARIA
FROM OFERTAS O
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

CREATE VIEW ALUNOS_MATRICULADOS AS
SELECT A.MATRICULA_ALUNO
	, A.NOME_ALUNO AS ALUNO
	, AO.SEMESTRE
	, O.HORARIO_INICIAL
	, O.HORARIO_FINAL
	, O.DIA_SEMANA
	, P.NOME_PROF AS PROFESSOR
	, D.NOME_DISCIPLINA
FROM ALUNO_OFERTAS AO
INNER JOIN ALUNOS A
ON AO.MATRICULA_ALUNO = A.MATRICULA_ALUNO
INNER JOIN OFERTAS O
ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

CREATE INDEX ALUNOS_NOME_IDX ON ALUNOS (NOME_ALUNO);
CREATE INDEX OFERTAS_DIA_IDX ON OFERTAS (DIA_SEMANA);
CREATE INDEX PROFESSORES_NOME_IDX ON PROFESSORES (NOME_PROF);
CREATE SEQUENCE DISCIPLINAS_SEQ;
CREATE SEQUENCE OFERTAS_SEQ;

ALTER TABLE ALUNOS ADD EMAIL_ALUNO VARCHAR2(200);
ALTER TABLE ALUNOS ADD CPF_ALUNO VARCHAR2(11);
ALTER TABLE PROFESSORES ADD CONTATO_PROF VARCHAR2(200);
ALTER TABLE OFERTAS ADD DATA_CRIACAO DATE;
ALTER TABLE ALUNOS MODIFY EMAIL_ALUNO VARCHAR2(250);
ALTER TABLE OFERTAS MODIFY DATA_CRIACAO DATE NOT NULL;
ALTER TABLE ALUNOS RENAME COLUMN MATRICULA_ALUNO TO MATRICULA_ALUNO;
ALTER TABLE ALUNOS RENAME COLUMN NOME_ALUNO TO NOME_ALUNO;
ALTER TABLE PROFESSORES RENAME COLUMN MATRICULA_PROF TO MATRICULA_PROF;
ALTER TABLE PROFESSORES RENAME COLUMN NOME_PROF TO NOME_PROF;
ALTER TABLE DISCIPLINAS RENAME COLUMN EMENTA TO EMENTA_DISCIPLINA;
ALTER TABLE ALUNO_OFERTAS RENAME COLUMN MATRICULA_ALUNO TO MATRICULA_ALUNO;
ALTER TABLE OFERTAS RENAME COLUMN MATRICULA_PROF TO MATRICULA_PROF;
ALTER TABLE TELEFONES RENAME TO TELEFONES_ALUNOS;
ALTER TABLE PROFESSORES DROP COLUMN CONTATO_PROF;
ALTER TABLE ALUNOS DROP COLUMN EMAIL_ALUNO;
ALTER TABLE ALUNOS DROP COLUMN CPF_ALUNO;
ALTER TABLE TELEFONES_ALUNOS ADD PRIMARY KEY (TELEFONE);
ALTER TABLE ALUNOS ADD PRIMARY KEY (MATRICULA_ALUNO);
ALTER TABLE ALUNO_OFERTAS ADD PRIMARY KEY (MATRICULA_ALUNO, CODIGO_OFERTA);
ALTER TABLE OFERTAS ADD PRIMARY KEY (CODIGO_OFERTA);
ALTER TABLE PROFESSORES ADD PRIMARY KEY (MATRICULA_PROF);
ALTER TABLE DISCIPLINAS ADD PRIMARY KEY (CODIGO_DISCIPLINA);
ALTER TABLE TELEFONES_ALUNOS ADD CONSTRAINT TELEFONE_ALUNO_FK FOREIGN KEY (MATRICULA_ALUNO) REFERENCES ALUNOS (MATRICULA_ALUNO);
ALTER TABLE ALUNO_OFERTAS ADD CONSTRAINT ALUNO_ALUNO_FK FOREIGN KEY (MATRICULA_ALUNO) REFERENCES ALUNOS (MATRICULA_ALUNO);
ALTER TABLE ALUNO_OFERTAS ADD CONSTRAINT ALUNO_OFERTA_FK FOREIGN KEY (CODIGO_OFERTA) REFERENCES OFERTAS (CODIGO_OFERTA);
ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_PROFESSOR_FK FOREIGN KEY (MATRICULA_PROF) REFERENCES PROFESSORES (MATRICULA_PROF);
ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_DISCIPLINAS_FK FOREIGN KEY (CODIGO_DISCIPLINA) REFERENCES DISCIPLINAS (CODIGO_DISCIPLINA);
ALTER TABLE DISCIPLINAS ADD CONSTRAINT DISCIPLINAS_DEPENDENCIA_FK FOREIGN KEY (CODIGO_DISCIPLINA_DEPENDENCIA) REFERENCES DISCIPLINAS (CODIGO_DISCIPLINA);

INSERT ALL
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40001, 'JOÃO GABRIEL', TO_DATE('04/02/1985', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40002, 'JOÃO JOSÉ', TO_DATE('31/12/2001', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40003, 'JOSÉ GABRIEL', TO_DATE('04/07/1999', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40004, 'ANTONIO JOSÉ', TO_DATE('27/09/1998', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40005, 'ANTONIO MARCIO', TO_DATE('20/04/1955', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40006, 'JOSÉ ANTÔNIO', TO_DATE('29/04/1955', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40007, 'MARCIO ANTONIO', TO_DATE('14/03/1967', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40008, 'JOÃO ANTONIO', TO_DATE('21/02/2002', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40009, 'MARCIO GABRIEL', TO_DATE('08/06/2009', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40010, 'GABRIEL ANTONIO', TO_DATE('01/01/1970', 'DD/MM/YYYY'))

SELECT * FROM DUAL;

COMMIT;

INSERT ALL
    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('11990897030', 40001)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('27990897031', 40001)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('33990897032', 40002)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('22990897033', 40010)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('27990897034', 40003)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('22990897035', 40006)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('11990897036', 40008)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('14990897037', 40003)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('18990897038', 40004)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('79990897039', 40007)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('83990897040', 40005)

    INTO TELEFONES_ALUNOS (TELEFONE, MATRICULA_ALUNO)
    VALUES ('81990897041', 40009)

SELECT * FROM DUAL;

COMMIT;

INSERT ALL
    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55124, 'CARLOS ANTONIO', 'MESTRADO')

    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55125, 'PAULO ANTONIO', 'DOUTORADO')

    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55126, 'PATRICIA CARMEN', 'ESPECIALIZAÇÃO')

    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55127, 'ALINE SANTOS', 'MESTRADO')

    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55128, 'ALICE DE SOUZA', 'MESTRADO')

    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55129, 'LUIZ CARLOS', 'DOUTORADO')

    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55130, 'LUCAS PEDRO', 'DOUTORADO')

    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55131, 'PEDRO HENRIQUE', 'MESTRADO')

    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55132, 'MARIA OLGA', 'DOUTORADO')

    INTO PROFESSORES (MATRICULA_PROF, NOME_PROF, FORMACAO)
    VALUES (55133, 'CAMILA PEREZ', 'ESPECIALIZAÇÃO')

SELECT * FROM DUAL;

COMMIT;

INSERT ALL
    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (31313, 'COMPUTER PROGRAMMING', 30, 'EMENTA DA DISCIPLINA COMPUTER PROGRAMMING', NULL)

    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (33412, 'MACHINE LEARNING', 80, 'EMENTA DA DISCIPLINA MACHINE LEARNING', NULL)

    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (75189, 'DATA MINING', 80, 'EMENTA DA DISCIPLINA DATA MINING', NULL)

    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (45812, 'DATA ANALYTICS', 40, 'EMENTA DA DISCIPLINA DATA ANALYTICS', NULL)

    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (18493, 'ROBOTIC', 60, 'EMENTA DA DISCIPLINA ROBOTIC', 31313)

    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (13131, 'DATABASE', 60, 'EMENTA DA DISCIPLINA DATABASE', 31313)

    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (48851, 'DATA SCIENCE', 80, 'EMENTA DA DISCIPLINA DATA SCIENCE', 75189)

    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (12345, 'NATURAL LANGUAGE PROCESSING', 80, 'EMENTA DA DISCIPLINA NATURAL LANGUAGE PROCESSING', 33412)

    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (55213, 'COMPUTER VISION', 80, 'EMENTA DA DISCIPLINA COMPUTER VISION', 33412)

    INTO DISCIPLINAS 
        (CODIGO_DISCIPLINA, NOME_DISCIPLINA, CARGA_HORARIA, EMENTA_DISCIPLINA, CODIGO_DISCIPLINA_DEPENDENCIA)
    VALUES 
        (85853, 'BIG DATA', 75, 'EMENTA DA DISCIPLINA BIG DATA', 75189)

SELECT * FROM DUAL;

COMMIT;

INSERT ALL
    INTO OFERTAS 
        (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROF, CODIGO_DISCIPLINA, DATA_CRIACAO)
    VALUES 
        (1418, TO_TIMESTAMP('18:45', 'HH24:MI'), TO_TIMESTAMP('22:00', 'HH24:MI'), 'SEGUNDA', 55125, 33412, SYSDATE)

    INTO OFERTAS 
        (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROF, CODIGO_DISCIPLINA, DATA_CRIACAO)
    VALUES 
        (1519, TO_TIMESTAMP('20:30', 'HH24:MI'), TO_TIMESTAMP('22:00', 'HH24:MI'), 'SEGUNDA', 55131, 12345, SYSDATE)

    INTO OFERTAS 
        (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROF, CODIGO_DISCIPLINA, DATA_CRIACAO)
    VALUES 
        (1742, TO_TIMESTAMP('18:45', 'HH24:MI'), TO_TIMESTAMP('20:15', 'HH24:MI'), 'TERÇA', 55125, 48851, SYSDATE)

    INTO OFERTAS 
        (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROF, CODIGO_DISCIPLINA, DATA_CRIACAO)
    VALUES 
        (1112, TO_TIMESTAMP('19:00', 'HH24:MI'), TO_TIMESTAMP('23:00', 'HH24:MI'), 'QUARTA', 55126, 55213, SYSDATE)

    INTO OFERTAS 
        (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROF, CODIGO_DISCIPLINA, DATA_CRIACAO)
    VALUES 
        (1313, TO_TIMESTAMP('17:00', 'HH24:MI'), TO_TIMESTAMP('21:00', 'HH24:MI'), 'QUARTA', 55130, 13131, SYSDATE)

    INTO OFERTAS 
        (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROF, CODIGO_DISCIPLINA, DATA_CRIACAO)
    VALUES 
        (1632, TO_TIMESTAMP('18:30', 'HH24:MI'), TO_TIMESTAMP('20:00', 'HH24:MI'), 'SEXTA', 55125, 12345, SYSDATE)

    INTO OFERTAS 
        (CODIGO_OFERTA, HORARIO_INICIAL, HORARIO_FINAL, DIA_SEMANA, MATRICULA_PROF, CODIGO_DISCIPLINA, DATA_CRIACAO)
    VALUES 
        (1674, TO_TIMESTAMP('19:30', 'HH24:MI'), TO_TIMESTAMP('21:30', 'HH24:MI'), 'QUINTA', 55133, 55213, SYSDATE)

SELECT * FROM DUAL;

COMMIT;

INSERT ALL
    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40001, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40001, 1519, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40001, 1313, 35, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40002, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40002, 1632, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40003, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40003, 1519, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40004, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40004, 1313, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40005, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40006, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40006, 1674, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40006, 1519, 35, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40007, 1674, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40007, 1313, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40008, 1313, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40008, 1519, 20, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40009, 1674, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

    INTO ALUNO_OFERTAS (MATRICULA_ALUNO, CODIGO_OFERTA, LIMITE_ALUNOS, SEMESTRE, DATA_INICIAL, DATA_FINAL)
    VALUES (40010, 1418, 40, '2022/2', TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('16/12/2022', 'DD/MM/YYYY'))

SELECT * FROM DUAL;

COMMIT;

UPDATE ALUNOS
SET DATA_NASCIMENTO = TO_DATE('29/04/2011', 'DD/MM/YYYY')
WHERE MATRICULA_ALUNO = 40004;

UPDATE PROFESSORES
SET FORMACAO = 'PHD'
WHERE MATRICULA_PROF = 55126;

UPDATE PROFESSORES
SET FORMACAO = 'MSC'
WHERE MATRICULA_PROF = 55126;

UPDATE DISCIPLINAS
SET CODIGO_DISCIPLINA_DEPENDENCIA = 31313
WHERE NOME_DISCIPLINA = 'MACHINE LEARNING';

UPDATE OFERTAS
SET MATRICULA_PROF = 55128
WHERE MATRICULA_PROF = 55125;


/* -- ESTUDAR ESSA PORRA AQUI
 UPDATE ALUNO_OFERTAS AO
SET AO.LIMITE_ALUNOS = 70
WHERE AO.CODIGO_OFERTA IN (
    SELECT O.CODIGO_OFERTA
    FROM OFERTAS O
    INNER JOIN DISCIPLINAS D
        ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA
    WHERE D.NOME_DISCIPLINA = 'NATURAL LANGUAGE PROCESSING'
);
 */
