DROP TABLE ALUNOS;
DROP TABLE TELEFONES;
DROP TABLE PROFESSORES;
DROP TABLE DISCIPLINAS;
DROP TABLE OFERTAS;
DROP TABLE ALUNO_OFERTAS;
CREATE TABLE ALUNOS(
	MATRICULA_ALUNO NUMBER NOT NULL,
	NOME_ALUNO VARCHAR2(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
);
CREATE TABLE TELEFONES(
	TELEFONE VARCHAR2(11) NOT NULL,
	MATRICULA_ALUNO NUMERIC NOT NULL
);
CREATE TABLE PROFESSORES(
	MATRICULA_PROF NUMERIC(5) NOT NULL,
	NOME_PROF VARCHAR2(100) NOT NULL,
	FORMACAO VARCHAR2(100) NOT NULL
);
CREATE TABLE DISCIPLINAS(
	CODIGO_DISCIPLINA NUMERIC NOT NULL,
	NOME_DISCIPLINA VARCHAR2(100) NOT NULL,
	CARGA_HORARIA NUMERIC(3) NOT NULL,
	EMENTA VARCHAR2(4000) NOT NULL,
	CODIGO_DISCIPLINA_DEPENDENCIA NUMERIC NULL
);
CREATE TABLE OFERTAS(
	CODIGO_OFERTA NUMERIC NOT NULL,
	HORARIO_INICIAL TIMESTAMP NOT NULL,
	HORARIO_FINAL TIMESTAMP NOT NULL,
	DIA_SEMANA VARCHAR2(20) NOT NULL,
	MATRICULA_PROF NUMERIC(5) NOT NULL,
	CODIGO_DISCIPLINA NUMERIC NOT NULL
);
CREATE TABLE ALUNO_OFERTAS(
	MATRICULA_ALUNO NUMERIC NOT NULL,
	CODIGO_OFERTA NUMERIC NOT NULL,
	LIMITE_ALUNOS NUMERIC NOT NULL,
	SEMESTRE VARCHAR2(6) NOT NULL,
	DATA_INICIAL DATE NOT NULL,
	DATA_FINAL DATE NOT NULL
);
