DROP TABLE ALUNOS;
DROP TABLE TELEFONES;
DROP TABLE PROFESSORES;
DROP TABLE DISCIPLINAS;
DROP TABLE OFERTAS;
DROP TABLE ALUNO_OFERTAS;
CREATE TABLE ALUNOS(
	MATRICULA_ALUNO NUMBER NOT NULL,
	NOME_ALUNO VARCHAR2(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
);
CREATE TABLE TELEFONES(
	TELEFONE VARCHAR2(11) NOT NULL,
	MATRICULA_ALUNO NUMERIC NOT NULL
);
CREATE TABLE PROFESSORES(
	MATRICULA_PROF NUMERIC(5) NOT NULL,
	NOME_PROF VARCHAR2(100) NOT NULL,
	FORMACAO VARCHAR2(100) NOT NULL
);
CREATE TABLE DISCIPLINAS(
	CODIGO_DISCIPLINA NUMERIC NOT NULL,
	NOME_DISCIPLINA VARCHAR2(100) NOT NULL,
	CARGA_HORARIA NUMERIC(3) NOT NULL,
	EMENTA VARCHAR2(4000) NOT NULL,
	CODIGO_DISCIPLINA_DEPENDENCIA NUMERIC NULL
);
CREATE TABLE OFERTAS(
	CODIGO_OFERTA NUMERIC NOT NULL,
	HORARIO_INICIAL TIMESTAMP NOT NULL,
	HORARIO_FINAL TIMESTAMP NOT NULL,
	DIA_SEMANA VARCHAR2(20) NOT NULL,
	MATRICULA_PROF NUMERIC(5) NOT NULL,
	CODIGO_DISCIPLINA NUMERIC NOT NULL
);
CREATE TABLE ALUNO_OFERTAS(
	MATRICULA_ALUNO NUMERIC NOT NULL,
	CODIGO_OFERTA NUMERIC NOT NULL,
	LIMITE_ALUNOS NUMERIC NOT NULL,
	SEMESTRE VARCHAR2(6) NOT NULL,
	DATA_INICIAL DATE NOT NULL,
	DATA_FINAL DATE NOT NULL
);

CREATE VIEW DISCIPLINAS_PROFESSOR AS
SELECT P.NOME_PROF AS PROFESSOR
	, P.FORMACAO
	, D.CODIGO_DISCIPLINA
	, D.NOME_DISCIPLINA
	, D.CARGA_HORARIA
FROM OFERTAS O
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

CREATE VIEW ALUNOS_MATRICULADOS AS
SELECT A.MATRICULA_ALUNO
	, A.NOME_ALUNO AS ALUNO
	, AO.SEMESTRE
	, O.HORARIO_INICIAL
	, O.HORARIO_FINAL
	, O.DIA_SEMANA
	, P.NOME_PROF AS PROFESSOR
	, D.NOME_DISCIPLINA
FROM ALUNO_OFERTAS AO
INNER JOIN ALUNOS A
ON AO.MATRICULA_ALUNO = A.MATRICULA_ALUNO
INNER JOIN OFERTAS O
ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

CREATE INDEX ALUNOS_NOME_IDX ON ALUNOS (NOME_ALUNO);
CREATE INDEX OFERTAS_DIA_IDX ON OFERTAS (DIA_SEMANA);
CREATE INDEX PROFESSORES_NOME_IDX ON PROFESSORES (NOME_PROF);
CREATE SEQUENCE DISCIPLINAS_SEQ;
CREATE SEQUENCE OFERTAS_SEQ;

ALTER TABLE ALUNOS ADD EMAIL_ALUNO VARCHAR2(200);
ALTER TABLE ALUNOS ADD CPF_ALUNO VARCHAR2(11);
ALTER TABLE PROFESSORES ADD CONTATO_PROF VARCHAR2(200);
ALTER TABLE OFERTAS ADD DATA_CRIACAO DATE;
ALTER TABLE ALUNOS MODIFY EMAIL_ALUNO VARCHAR2(250);
ALTER TABLE OFERTAS MODIFY DATA_CRIACAO DATE NOT NULL;
ALTER TABLE ALUNOS RENAME COLUMN MATRICULA_ALUNO TO MATRICULA_ALUNO;
ALTER TABLE ALUNOS RENAME COLUMN NOME_ALUNO TO NOME_ALUNO;
ALTER TABLE PROFESSORES RENAME COLUMN MATRICULA_PROF TO MATRICULA_PROF;
ALTER TABLE PROFESSORES RENAME COLUMN NOME_PROF TO NOME_PROF;
ALTER TABLE DISCIPLINAS RENAME COLUMN EMENTA TO EMENTA_DISCIPLINA;
ALTER TABLE ALUNO_OFERTAS RENAME COLUMN MATRICULA_ALUNO TO MATRICULA_ALUNO;
ALTER TABLE OFERTAS RENAME COLUMN MATRICULA_PROF TO MATRICULA_PROF;
ALTER TABLE TELEFONES RENAME TO TELEFONES_ALUNOS;
ALTER TABLE PROFESSORES DROP COLUMN CONTATO_PROF;
ALTER TABLE ALUNOS DROP COLUMN EMAIL_ALUNO;
ALTER TABLE ALUNOS DROP COLUMN CPF_ALUNO;
ALTER TABLE TELEFONES_ALUNOS ADD PRIMARY KEY (TELEFONE);
ALTER TABLE ALUNOS ADD PRIMARY KEY (MATRICULA_ALUNO);
ALTER TABLE ALUNO_OFERTAS ADD PRIMARY KEY (MATRICULA_ALUNO, CODIGO_OFERTA);
ALTER TABLE OFERTAS ADD PRIMARY KEY (CODIGO_OFERTA);
ALTER TABLE PROFESSORES ADD PRIMARY KEY (MATRICULA_PROF);
ALTER TABLE DISCIPLINAS ADD PRIMARY KEY (CODIGO_DISCIPLINA);
ALTER TABLE TELEFONES_ALUNOS ADD CONSTRAINT TELEFONE_ALUNO_FK FOREIGN KEY (MATRICULA_ALUNO) REFERENCES ALUNOS (MATRICULA_ALUNO);
ALTER TABLE ALUNO_OFERTAS ADD CONSTRAINT ALUNO_ALUNO_FK FOREIGN KEY (MATRICULA_ALUNO) REFERENCES ALUNOS (MATRICULA_ALUNO);
ALTER TABLE ALUNO_OFERTAS ADD CONSTRAINT ALUNO_OFERTA_FK FOREIGN KEY (CODIGO_OFERTA) REFERENCES OFERTAS (CODIGO_OFERTA);
ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_PROFESSOR_FK FOREIGN KEY (MATRICULA_PROF) REFERENCES PROFESSORES (MATRICULA_PROF);
ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_DISCIPLINAS_FK FOREIGN KEY (CODIGO_DISCIPLINA) REFERENCES DISCIPLINAS (CODIGO_DISCIPLINA);
ALTER TABLE DISCIPLINAS ADD CONSTRAINT DISCIPLINAS_DEPENDENCIA_FK FOREIGN KEY (CODIGO_DISCIPLINA_DEPENDENCIA) REFERENCES DISCIPLINAS (CODIGO_DISCIPLINA);

INSERT ALL
    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40001, 'JOÃO GABRIEL', TO_DATE('04/02/1985', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40002, 'JOÃO JOSÉ', TO_DATE('31/12/2001', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40003, 'JOSÉ GABRIEL', TO_DATE('04/07/1999', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40004, 'ANTONIO JOSÉ', TO_DATE('27/09/1998', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40005, 'ANTONIO MARCIO', TO_DATE('20/04/1955', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40006, 'JOSÉ ANTÔNIO', TO_DATE('29/04/1955', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40007, 'MARCIO ANTONIO', TO_DATE('14/03/1967', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40008, 'JOÃO ANTONIO', TO_DATE('21/02/2002', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40009, 'MARCIO GABRIEL', TO_DATE('08/06/2009', 'DD/MM/YYYY'))

    INTO ALUNOS (MATRICULA_ALUNO, NOME_ALUNO, DATA_NASCIMENTO)
    VALUES (40010, 'GABRIEL ANTONIO', TO_DATE('01/01/1970', 'DD/MM/YYYY'))

SELECT * FROM DUAL;
