ALTER TABLE ALUNOS RENAME COLUMN MATRICULA_ALUNO TO MATRICULA_ALUNO;
ALTER TABLE ALUNOS RENAME COLUMN NOME_ALUNO TO NOME_ALUNO;
ALTER TABLE PROFESSORES RENAME COLUMN MATRICULA_PROF TO MATRICULA_PROF;
ALTER TABLE PROFESSORES RENAME COLUMN NOME_PROF TO NOME_PROF;
ALTER TABLE DISCIPLINAS RENAME COLUMN EMENTA TO EMENTA_DISCIPLINA;
ALTER TABLE ALUNO_OFERTAS RENAME COLUMN MATRICULA_ALUNO TO MATRICULA_ALUNO;
ALTER TABLE OFERTAS RENAME COLUMN MATRICULA_PROF TO MATRICULA_PROF;
