CREATE VIEW DISCIPLINAS_PROFESSOR AS
SELECT P.NOME_PROF AS PROFESSOR
	, P.FORMACAO
	, D.CODIGO_DISCIPLINA
	, D.NOME_DISCIPLINA
	, D.CARGA_HORARIA
FROM OFERTAS O
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;

CREATE VIEW ALUNOS_MATRICULADOS AS
SELECT A.MATRICULA_ALUNO
	, A.NOME_ALUNO AS ALUNO
	, AO.SEMESTRE
	, O.HORARIO_INICIAL
	, O.HORARIO_FINAL
	, O.DIA_SEMANA
	, P.NOME_PROF AS PROFESSOR
	, D.NOME_DISCIPLINA
FROM ALUNO_OFERTAS AO
INNER JOIN ALUNOS A
ON AO.MATRICULA_ALUNO = A.MATRICULA_ALUNO
INNER JOIN OFERTAS O
ON AO.CODIGO_OFERTA = O.CODIGO_OFERTA
INNER JOIN PROFESSORES P
ON O.MATRICULA_PROF = P.MATRICULA_PROF
INNER JOIN DISCIPLINAS D
ON O.CODIGO_DISCIPLINA = D.CODIGO_DISCIPLINA;